### ISSUE TITLE
text inside descriptions in task is not correctly written

### ISSUE THREAD

**Issue by bilbo-the-hobbit** [Befox/cdav#9]
Hello,

the text put inside the tasks, that sould be calendar events see https://github.com/Befox/cdav/issues/8 should be only text and not html

Cheers

![caldav-taches-agendas1](https://cloud.githubusercontent.com/assets/243766/24598767/7c2e2a0a-184d-11e7-97df-f637df09c51d.png)

**Comment by jpfox** [comment]
Hello,

I think you use a specific module that permit to enter HTML code in description field on Dolibarr... I haven't find this option ??

**Comment by bilbo-the-hobbit** [comment]
hello,

dolibarr allow you to use an editor that allow us to put bold / underline etc in text box, its by default in dolibarr. its in  Modules> Supplementary modules 

Cheers

**Comment by jpfox** [comment]
Ok, so we have to options : 

- cdav clean note to remove html tags, but if you modify an event in Thunderbird (or other caldav client), you loose text decoration (because when an event is modified, we grab all information to update Dolibarr event.
- cdav do not touch html code but it is displayed as it does actually.

There is no magic solution for this problem.
